# Generated by Django 3.2.6 on 2021-08-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=60, verbose_name='ФИО')),
                ('subject', models.CharField(max_length=90, verbose_name='Причина обращения ')),
                ('r_date', models.DateField(verbose_name='Дата приема')),
                ('time', models.CharField(max_length=5, verbose_name='Время приема')),
                ('stol', models.IntegerField(verbose_name='Стол')),
            ],
        ),
    ]
