# Generated by Django 3.2.6 on 2021-09-19 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('priem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=60, verbose_name='ФИО')),
                ('stol', models.IntegerField(verbose_name='Стол')),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stol', models.IntegerField(verbose_name='Стол')),
                ('date1', models.DateField(verbose_name='Отпуск с')),
                ('date2', models.DateField(verbose_name='Отпуск до')),
                ('fio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='priem.stol', verbose_name='ФИО ')),
            ],
        ),
    ]
